### ISSUE TITLE
try to deploy cloudlfare pages

### ISSUE THREAD

**Issue by wanghaisheng** [mearashadowfax/OpenStove#112]
[vite]: Rollup failed to resolve import "@preline/tooltip/index.js" from "/opt/buildhome/repo/src/components/Pagination.astro?astro&type=script&index=0&lang.ts".

If you do want to externalize this module explicitly add it t
`build.rollupOptions.external`
--

**Comment by mearashadowfax** [comment]
Hey @wanghaisheng! Can you check if it is working now?

**Comment by wanghaisheng** [comment]
works like magic , why  keep those files under folder script

**Comment by mearashadowfax** [comment]
You mean in the public dir? You can delete the `scripts` folder, it is not used anywhere in the project.

**Comment by wanghaisheng** [comment]
got that, when i found it  i am kinda of confused
