### ISSUE TITLE
Missing `Meta.astro` in layout

### ISSUE THREAD

**Issue by bholmesdev** [mearashadowfax/OpenStove#25]
Unable to build due to missing `Meta.astro` [referenced in the main layout file](https://github.com/mearashadowfax/OpenStove/blob/main/src/layouts/MainLayout.astro#L4).

**Comment by mearashadowfax** [comment]
Hello @bholmesdev, thank you for pointing this out! I've just added the missing Meta.astro component to the project.

**Comment by bholmesdev** [comment]
Hey thanks for fixing this @mearashadowfax! Unfortunately, I now see a missing image when building this repo locally: `../images/hero-image.svg`. In fact, I don't see a `src/images/` directory looking at the source. Do you mind double checking that all resources are present and the production build succeeds? I would love to contribute a recipe and want to test my work.

**Comment by mearashadowfax** [comment]
Hey, @bholmesdev ! You're right, the `src/images/` directory is currently excluded due to copyright restrictions on the images used, I'm afraid it is not possible to test locally. However, if you've followed the `Recipe Format Guidelines`, there's nothing to worry about. We'd love to see your recipe contribution!

**Comment by mearashadowfax** [comment]
@bholmesdev, I've made some adjustments, now you should be able to see and test your recipes locally.

**Comment by bholmesdev** [comment]
@mearashadowfax appreciate those component changes! The only issue I'm seeing is with a missing `src/images/placeholder.png`. Removing the import for this file shows the website correctly. Is it possible to add this file (ignoring all other images) without copyright concerns?

I also understand that local development testing isn't required. However, it's helpful to test locally to ensure a) the Markdown file is formatted correctly (YAML is frustrating at times) and b) the recipe renders how I expect.

**Comment by mearashadowfax** [comment]
@bholmesdev Ah, that pesky `.png` was hiding in the `.gitignore` list! Fixed that, thanks for pointing it out!

Yes, local testing might not be mandatory, but you're absolutely right - it's super helpful to see and test everything locally. By the way, huge thanks for being the first one to add a recipe and providing such insightful feedback!  Really appreciate it.

**Comment by bholmesdev** [comment]
Ah for sure! Appreciate that @mearashadowfax. Remember seeing Open Stove on the showcase discussion a while back and bookmarked to send a recipe. I'll let other people know to see if we can drive some contribution :)
